apiVersion: v1
kind: ConfigMap
metadata:
  name: project-config
data:
  SERVER_PORT: "3000"
  IMAGE_FILE: "/usr/src/app/files/image.jpg"
  IMAGE_MAX_AGE_SECONDS: "600"
  IMAGE_URL: "https://picsum.photos/1200"
  TODO_BACKEND_URL: "http://todo-backend-svc:2349"
  MAX_TODO_LENGTH: "140"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "todo"
  DB_HOST: "postgres-svc"
  DB_NAME: "todo"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  NATS_URL: "nats://my-nats.nats.svc.cluster.local:4222"
  NATS_SUBJECT: "todos"
  NATS_QUEUE_GROUP: "broadcaster"
  TELEGRAM_API_URL: "https://api.telegram.org"
  BROADCAST_TARGET: "telegram"
