apiVersion: batch/v1
kind: CronJob
metadata:
  name: create-todo-job
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: create-todo
              image: PROJECT/BACKEND
              imagePullPolicy: IfNotPresent
              command: ["python3", "create_todo.py"]
              envFrom:
                - configMapRef:
                    name: project-config
              resources:
                requests:
                  cpu: "10m"
                  memory: "64Mi"
                limits:
                  cpu: "100m"
                  memory: "128Mi"
          restartPolicy: Never
