apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- configmap.yaml
- persistentvolumeclaim-gke.yaml
- gateway.yaml
- httproute.yaml
- todo-app.yaml
- todo-broadcaster.yaml
- todo-backend.yaml
- statefulset.yaml
- cronjob-create-todo.yaml
