apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging
resources:
- namespace.yaml
- ../../base
patches:
- path: configmap.yaml
images:
- name: PROJECT/APP
  newName: europe-north1-docker.pkg.dev/dwk-gke-508413/dwk-repo/todo-app
  newTag: main-9e4234d9907130b1d87db260954f99545123618a
- name: PROJECT/BACKEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-508413/dwk-repo/todo-backend
  newTag: main-9e4234d9907130b1d87db260954f99545123618a
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/dwk-gke-508413/dwk-repo/todo-broadcaster
  newTag: main-9e4234d9907130b1d87db260954f99545123618a
