apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging
resources:
- namespace.yaml
- ../../base
patches:
- path: configmap.yaml
images:
- name: PROJECT/APP
  newName: europe-north1-docker.pkg.dev/dwk-gke-508413/dwk-repo/todo-app
  newTag: main-f23c323cf27b83beda4ae894d29943c0eedf72cf
- name: PROJECT/BACKEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-508413/dwk-repo/todo-backend
  newTag: main-f23c323cf27b83beda4ae894d29943c0eedf72cf
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/dwk-gke-508413/dwk-repo/todo-broadcaster
  newTag: main-f23c323cf27b83beda4ae894d29943c0eedf72cf
