apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-db-job
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: shared-volume
              emptyDir: {}
            - name: secret-volume
              secret:
                secretName: storage-sa-key
          initContainers:
            - name: create-backup
              image: postgres:17-alpine
              envFrom:
                - configMapRef:
                    name: project-config
              env:
                - name: PGPASSWORD
                  valueFrom:
                    configMapKeyRef:
                      name: project-config
                      key: DB_PASSWORD
              command: [
                "sh", "-c", "mkdir -p /usr/src/app/files/backup && \
                pg_dump -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER} -d ${DB_NAME} -F c -f /usr/src/app/files/backup/${DB_NAME}_$(date +%Y-%m-%d).dump"
              ]
              volumeMounts:
                - mountPath: /usr/src/app/files
                  name: shared-volume
              resources:
                requests:
                  cpu: "10m"
                  memory: "64Mi"
                limits:
                  cpu: "100m"
                  memory: "128Mi"
          containers:
            - name: store-backup
              image: google/cloud-sdk:alpine
              command: [
                "sh", "-c",
                "gcloud auth activate-service-account --key-file=/usr/src/app/secret/key.json && \
                gcloud storage cp /usr/src/app/files/backup/*.dump gs://dwk-gke-bucket/"
              ]
              volumeMounts:
                - mountPath: /usr/src/app/files
                  name: shared-volume
                - mountPath: /usr/src/app/secret
                  name: secret-volume
              resources:
                requests:
                  cpu: "10m"
                  memory: "64Mi"
                limits:
                  cpu: "100m"
                  memory: "128Mi"
