apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-prod
resources:
- namespace.yaml
- ../../base
- cronjob-backup-db.yaml
images:
- name: PROJECT/APP
  newName: europe-north1-docker.pkg.dev/dwk-gke-508413/dwk-repo/todo-app
  newTag: "4.10"
- name: PROJECT/BACKEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-508413/dwk-repo/todo-backend
  newTag: "4.10"
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/dwk-gke-508413/dwk-repo/todo-broadcaster
  newTag: "4.10"
